services:
  app:
    build:
      context: .. # Build context is the project root
      dockerfile: ./docker/Dockerfile # Path to the Dockerfile
    ports:
      - "8000:8000" # Backend port
      - "5173:5173" # Frontend port
    volumes:
      - ../backend:/app/backend # Mount backend for live reloading
      - ../frontend:/app/frontend # Mount frontend for live reloading
      - /app/frontend/node_modules # Exclude node_modules from host mount
    environment:
      # Add any necessary environment variables for the application
      PYTHONUNBUFFERED: 1
      VITE_API_URL: http://localhost:8000 # Frontend will use this to connect to backend
      APP_GITHUB_REPO_URL: ${APP_GITHUB_REPO_URL:-}
      APP_GITHUB_PAT: ${APP_GITHUB_PAT:-}
      APP_CLONE_DIR: /tmp/repo_clone
